Issue #22: Build failing
## Issue
Build was failing with message

```
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (115)
```

## Changes
- Updates `gulp-sass` package `v4.0.2` --> `v5.1.0`
- Installed `dart-sass@v1.25.0`
  - required to pass into newer versions of  `gulp-sass`
- Updates import of `gulp-sass` to pass in `dart-sass`

## Outcome

Build is passing locally